from app_models import Family

def load():
    Family(name='Browns',city='Brooklyn',state='New York').put()
    Family(name='Blacks',city='Brooklyn',state='New York').put()
    Family(name='Smiths',city='Brooklyn',state='New York').put()
    Family(name='Vargas',city='Brooklyn',state='New York').put()
    Family(name='Lawrences',city='Brooklyn',state='New York').put()
    Family(name='Ikies',city='Brooklyn',state='New York').put()
    Family(name='Murays',city='Topeka',state='Kansas').put()
    Family(name='Vasques',city='Topeka',state='Kansas').put()
    Family(name='Banks',city='Topeka',state='Kansas').put()
    Family(name='Fins',city='Topeka',state='Kansas').put()
    Family(name='Ray',city='Topeka',state='Kansas').put()
    Family(name='Taylor',city='Madison',state='Wisonsin').put()
    Family(name='Samuel',city='Madison',state='Wisonsin').put()
    Family(name='Pete',city='Madison',state='Wisonsin').put()
    Family(name='Cambell',city='Queens',state='Wisonsin').put()
    Family(name='Ramsay',city='Queens',state='Wisonsin').put()
    Family(name='Bolton',city='Queens',state='New York').put()
    Family(name='Pickit',city='Queens',state='New York').put()
    Family(name='Cathoun',city='Queens',state='New York').put()
    Family(name='Bates',city='Philadephia',state='Pennsylvania').put()
    Family(name='Bulat',city='Philadephia',state='Pennsylvania').put()
    Family(name='Pavlov',city='Philadephia',state='Pennsylvania').put()
    Family(name='Stepanov',city='Philadephia',state='Pennsylvania').put()
    Family(name='Morovich',city='Philadephia',state='Pennsylvania').put()