from app_models import Family

def load():
    Family(name='Brown',city='Brooklyn',state='New York').put()
    Family(name='Black',city='Brooklyn',state='New York').put()
    Family(name='Smith',city='Brooklyn',state='New York').put()
    Family(name='Vargas',city='Brooklyn',state='New York').put()
    Family(name='Lawrence',city='Brooklyn',state='New York').put()
    Family(name='Ikie',city='Brooklyn',state='New York').put()
    Family(name='Murays',city='Topeka',state='Kansas').put()
    Family(name='Vasques',city='Topeka',state='Kansas').put()
    Family(name='Banks',city='Topeka',state='Kansas').put()
    Family(name='Fins',city='Topeka',state='Kansas').put()
    Family(name='Ray',city='Topeka',state='Kansas').put()
    Family(name='Taylor',city='Madison',state='Wisonsin').put()
    Family(name='Noah',city='Madison',state='Wisonsin').put()
    Family(name='Shammy',city='Madison',state='Wisonsin').put()
    Family(name='Samuels',city='Madison',state='Wisonsin').put()
    Family(name='Pete',city='Madison',state='Wisonsin').put()
    Family(name='Cambell',city='Queens',state='New York').put()
    Family(name='Ramsay',city='Queens',state='New York').put()
    Family(name='Bolton',city='Queens',state='New York').put()
    Family(name='Pickit',city='Queens',state='New York').put()
    Family(name='Cathoun',city='Queens',state='New York').put()
    Family(name='Bates',city='Philadephia',state='Pennsylvania').put()
    Family(name='Bulat',city='Philadephia',state='Pennsylvania').put()
    Family(name='Pavlov',city='Philadephia',state='Pennsylvania').put()
    Family(name='Stepanov',city='Philadephia',state='Pennsylvania').put()
    Family(name='Morovich',city='Philadephia',state='Pennsylvania').put()